import test from 'node:test';
import assert from 'node:assert/strict';
import {metadataFrom,extractModel,semanticSignature,keyLabel,columnInfo,selectView} from '../web/model.mjs';
function db(){const entity=(id,attributes,alias='')=>({id,attributes,alias,cssStyles:[],cssCompiledStyles:[]});const entities=new Map([
    ['ACCOUNT',entity('e0',[{name:'id',type:'uuid',keys:['PK']},{name:'tenant',type:'int',keys:['UK']},{name:'email',type:'varchar(255)',keys:['UK']},{name:'bio',type:'text?',keys:[]}],'계정')],
    ['ENTRY',entity('e1',[{name:'id',type:'uuid',keys:['PK']},{name:'account_id',type:'uuid?',keys:['FK']}])]]);
    return {getEntities:()=>entities,getData:()=>({nodes:[{id:'e0',parentId:'accounts'},{id:'e1'}],config:{}}),getSubGraphs:()=>[{id:'accounts',title:'계정 영역',nodes:['ACCOUNT']}],getDirection:()=> 'LR',getRelationships:()=>[{entityA:'e0',entityB:'e1',roleA:'작성',relSpec:{cardB:'ZERO_OR_ONE',cardA:'ZERO_OR_MORE',relType:'NON_IDENTIFYING'}}]};}
const meta=()=>({table:'ACCOUNT',columns:{email:{nullable:false}},unique:[{name:'uq_tenant_email',columns:['tenant','email']}]});
const source=m=>`%% @db-camp ${JSON.stringify(m)}\nerDiagram`;
test('Mermaid nullable, alias, direction, subgraphs and cardinality preserve meanings',()=>{const m=extractModel(db(),source(meta()));const a=m.entities[0];assert.equal(a.title,'계정');assert.equal(a.attributes[3].type,'text');assert.equal(columnInfo(a,a.attributes[3]).nullable,true);assert.equal(columnInfo(a,a.attributes[1]).nullable,null);assert.equal(columnInfo(a,a.attributes[0]).nullable,false);assert.equal(m.relationships[0].cardA,'ZERO_OR_ONE');assert.equal(m.relationships[0].cardB,'ZERO_OR_MORE');assert.equal(m.direction,'LR');assert.equal(m.groups[0].id,'accounts');});
test('composite UK membership is explicit rather than two separate uniques',()=>{const m=extractModel(db(),source(meta()));assert.equal(keyLabel(m.entities[0],m.entities[0].attributes[1]),'UK:uq_tenant_email');assert.equal(m.entities[0].metadata.unique[0].columns.length,2);});
test('visual settings do not change semantic identity; constraints and titles do',()=>{const first=extractModel(db(),source(meta())),signature=semanticSignature(first);first.direction='TB';first.entities[0].styles=['fill:red'];first.visual={rankSpacing:200};assert.equal(semanticSignature(first),signature);first.title='new design title';assert.notEqual(semanticSignature(first),signature);first.title='';first.entities[0].metadata.columns.email.nullable=true;assert.notEqual(semanticSignature(first),signature);});
test('layout metadata is parsed but cannot change the design semantic signature',()=>{const original=source(meta()),a=extractModel(db(),original),b=extractModel(db(),original+'\n%% @db-camp-layout {"version":1,"mode":"screen","aspect":1.4,"nodes":{"ACCOUNT":{"x":64,"y":300}},"edges":{}}');assert.equal(b.placement.nodes.ACCOUNT.y,300);assert.equal(semanticSignature(a),semanticSignature(b));assert.deepEqual(a.entities,b.entities);assert.deepEqual(a.relationships,b.relationships);});
test('metadata mistakes reject missing columns, inconsistent nullability, and duplicate tables',()=>{for(const m of [{table:'MISSING'},{table:'ACCOUNT',columns:{missing:{nullable:false}}},{table:'ACCOUNT',columns:{id:{nullable:true}}},{table:'ACCOUNT',columns:{bio:{nullable:false}}},{table:'ACCOUNT',unique:[{name:'uq',columns:['missing']}]},{table:'ACCOUNT',other:1}])assert.throws(()=>extractModel(db(),source(m)),/설계 정보 오류/);assert.throws(()=>metadataFrom(`${source(meta())}\n${source(meta())}`),/중복/);assert.throws(()=>metadataFrom('%% @db-camp {broken'),/JSON 오류/);});
test('metadata names cannot mutate object prototypes',()=>{const m=metadataFrom('%% @db-camp {"table":"__proto__","description":"plain data"}');assert.equal(Object.getPrototypeOf(m),null);assert.equal(m.__proto__.description,'plain data');assert.equal({}.description,undefined);});
test('FK mappings validate counts and targets; advisory review is not a schema mutation',()=>{const m={table:'ENTRY',foreignKeys:[{name:'fk_account',columns:['account_id'],references:{table:'ACCOUNT',columns:['id']},label:'작성'}]};const model=extractModel(db(),source(m));assert(!model.warnings.some(w=>w.includes('FK 참조 컬럼')));m.foreignKeys[0].references.columns=['missing'];assert.throws(()=>extractModel(db(),source(m)),/참조 대상/);});
test('subject and neighbor views preserve the full model and omit out-of-view edges explicitly',()=>{const full=extractModel(db(),source(meta()));const subject=selectView(full,'group:accounts');assert.equal(subject.entities.length,1);assert.equal(subject.relationships.length,0);assert.equal(selectView(full,'entity:ACCOUNT').entities.length,2);assert.equal(full.entities.length,2);assert.throws(()=>selectView(full,'group:missing'),/테이블이 없습니다/);});
