import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,writeFile,readFile,rename} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import path from 'node:path';
import {PNG} from 'pngjs';
import {Session} from '../runtime/server.mjs';
const source='erDiagram\n A {\n int id PK\n }\n';
async function fixture(){const dir=await mkdtemp(path.join(tmpdir(),'db-camp-review-')),file=path.join(dir,'sample.mmd'),reviewFile=path.join(dir,'review.json');await writeFile(file,source);return {file,reviewFile,s:await Session.create(file,{reviewFile})};}
async function ready(s,j=s.jobs.get(s.current)){const p=new PNG({width:1,height:1});p.data.fill(255);return s.act('ui','report',{id:j.id,source_hash:j.source_hash,theme:j.theme,png:PNG.sync.write(p).toString('base64'),svg:'<svg xmlns="http://www.w3.org/2000/svg"/>',semantic:'{}'});}
async function stage(s,content=s.content){const j=await s.act('draw','stage',{version:s.version,saved_hash:s.savedHash,content});await ready(s,s.jobs.get(j.id));return j;}
async function reviewed(s){const j=await stage(s);await s.act('draw','preview',{},new URLSearchParams({id:j.id}));await s.act('draw','commit',{id:j.id,review:'pass',findings:['Protocol fixture only']});}
test('first image review unlocks later automatic commits without image retrieval',async()=>{const {s,file}=await fixture();assert.equal((await s.state()).review_mode,'strict');const initial=await stage(s);await assert.rejects(s.act('draw','commit',{id:initial.id,review:'automatic',findings:[]}),/reviewed/);await s.act('draw','preview',{},new URLSearchParams({id:initial.id}));await s.act('draw','commit',{id:initial.id,review:'pass',findings:[]});const next=await stage(s,source+'\n B\n');assert.equal(s.jobs.get(next.id).seen,undefined);await s.act('draw','commit',{id:next.id,review:'automatic',findings:[]});assert.equal(await readFile(file,'utf8'),source+'\n B\n');assert.equal((await s.state()).review_mode,'automatic');});
test('render error is latched across a successful retry and runtime restart until image review',async()=>{const {s,file,reviewFile}=await fixture();await reviewed(s);await s.act('ui','draft',{version:s.version,content:'broken'});await s.act('ui','report',{id:s.current,source_hash:s.jobs.get(s.current).source_hash,error:'parse failed'});assert.equal(await readFile(file,'utf8'),source);assert(s.jobs.get(s.lastGood).png);await s.act('ui','draft',{version:s.version,content:source+'\n B\n'});await ready(s);assert.equal((await s.state()).review_mode,'strict');const next=await stage(s);await assert.rejects(s.act('draw','commit',{id:next.id,review:'automatic',findings:[]}),/reviewed/);const restarted=await Session.create(file,{reviewFile});assert.equal((await restarted.state()).review_mode,'strict');await reviewed(restarted);assert.equal((await (await Session.create(file,{reviewFile})).state()).review_mode,'automatic');});
test('clean polling adopts atomic external saves and renders new source without a model',async()=>{const {s,file}=await fixture();await reviewed(s);const before=s.version,temp=file+'.tmp',next=source+'\n B {\n uuid id PK\n }\n';await writeFile(temp,next);await rename(temp,file);const jobs=await s.act('ui','jobs',{},new URLSearchParams('clean=1'));assert.equal(jobs.state.file_conflict,false);assert.equal(jobs.state.version,before+1);assert.equal(jobs.state.content,next);assert.equal(jobs.jobs.length,1);assert.equal(jobs.jobs[0].content,next);await ready(s);assert.equal((await s.state()).review_mode,'automatic');assert.equal(await readFile(file,'utf8'),next);});
test('external changes never replace dirty drafts or candidates under review',async()=>{for(const kind of ['draft','candidate']){const {s,file}=await fixture();await reviewed(s);if(kind==='draft')await s.act('ui','draft',{version:s.version,content:source+'\n DRAFT\n'});else await stage(s,source+'\n CANDIDATE\n');const before=s.version,content=s.content,external=source+'\n EXTERNAL\n';await writeFile(file,external);const j=await s.act('ui','jobs',{},new URLSearchParams('clean=1'));assert.equal(j.state.file_conflict,true);assert.equal(s.version,before);assert.equal(s.content,content);await assert.rejects(s.act('draw','sync'),/draft|review in progress/);assert.equal(await readFile(file,'utf8'),external);}});
test('missing or corrupt review records require first review and timeout revokes automatic mode',async()=>{const {s,file,reviewFile}=await fixture();await reviewed(s);assert.equal((await (await Session.create(file,{reviewFile})).state()).review_mode,'automatic');await writeFile(reviewFile,'not json');assert.equal((await (await Session.create(file,{reviewFile})).state()).review_mode,'strict');await s.act('ui','draft',{version:s.version,content:source+'\n B\n'});s.jobs.get(s.current).created=Date.now()-31000;assert.equal((await s.state()).review_mode,'strict');assert.equal((await (await Session.create(file,{reviewFile})).state()).review_mode,'strict');});
test('malformed render output revokes automatic mode without replacing the last good image',async()=>{const {s,file}=await fixture();await reviewed(s);const j=await s.act('draw','stage',{version:s.version,saved_hash:s.savedHash,content:source+'\n B\n'});await assert.rejects(s.act('ui','report',{id:j.id,source_hash:j.source_hash,theme:'light',png:'invalid',svg:'<svg/>',semantic:'{}'}),/PNG/);assert.equal((await s.state()).review_mode,'strict');assert(s.jobs.get(s.lastGood).png);assert.equal(await readFile(file,'utf8'),source);});
