import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,writeFile,readFile,stat,readdir,symlink,unlink} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import path from 'node:path';
import {PNG} from 'pngjs';
import {Session,startServer} from '../runtime/server.mjs';
const source='erDiagram\n A {\n int id PK\n }\n';
async function fixture(){const dir=await mkdtemp(path.join(tmpdir(),'db-camp-state-')),file=path.join(dir,'독립 이름.mmd');await writeFile(file,source);return {dir,file,s:await Session.create(file)};}
function image(job,semantic='{}'){const png=new PNG({width:2,height:2});png.data.fill(255);return {id:job.id,source_hash:job.source_hash,theme:job.theme,png:PNG.sync.write(png).toString('base64'),svg:'<svg xmlns="http://www.w3.org/2000/svg" width="1" height="1"/>',semantic};}
async function ready(s,job=s.jobs.get(s.current),semantic='{}'){return s.act('ui','report',image(job,semantic));}
test('valid direct edit saves atomically while error drafts retain original and previous image',async()=>{const {s,file,dir}=await fixture();await ready(s);const before=(await stat(file)).mtimeMs;await s.act('ui','theme',{version:s.version,theme:'dark'});await ready(s);assert.equal((await stat(file)).mtimeMs,before);await s.act('ui','draft',{version:s.version,content:'broken'});await s.act('ui','report',{id:s.current,source_hash:s.jobs.get(s.current).source_hash,error:'syntax failure'});assert.equal(await readFile(file,'utf8'),source);assert(s.jobs.get(s.lastGood).png);assert.equal(s.content,'broken');assert.deepEqual(await readdir(dir),[path.basename(file)]);});
test('candidate never touches source, requires draw image retrieval and preserves image after commit',async()=>{const {s,file}=await fixture();const j=await s.act('draw','stage',{version:s.version,saved_hash:s.savedHash,content:source+'\n B\n'});await ready(s,s.jobs.get(j.id));await assert.rejects(s.act('draw','commit',{id:j.id,review:'pass',findings:[]}),/retrieved/);await s.act('discuss','preview',{},new URLSearchParams({id:j.id}));await assert.rejects(s.act('draw','commit',{id:j.id,review:'pass',findings:[]}),/retrieved/);assert.equal(await readFile(file,'utf8'),source);await s.act('draw','preview',{},new URLSearchParams({id:j.id}));await s.act('draw','commit',{id:j.id,review:'pass',findings:[]});assert.equal(await readFile(file,'utf8'),source+'\n B\n');assert((await s.act('discuss','preview')).png);});
test('human edits cancel candidates and stale render reports are rejected',async()=>{const {s,file}=await fixture();const job=await s.act('draw','stage',{version:s.version,saved_hash:s.savedHash,content:source+'\n B'});await s.act('ui','draft',{version:s.version,content:source+'\n C'});await assert.rejects(ready(s,s.jobs.get(job.id)),/stale/);assert.equal(s.jobs.get(job.id).status,'cancelled');assert.equal(await readFile(file,'utf8'),source);});
test('external file changes are readable but cannot be overwritten',async()=>{const {s,file}=await fixture();const j=await s.act('draw','stage',{version:s.version,saved_hash:s.savedHash,content:source+'\n B'});await ready(s,s.jobs.get(j.id));await s.act('draw','preview',{},new URLSearchParams({id:j.id}));await writeFile(file,'erDiagram\n EXTERNAL\n');assert.equal((await s.state()).disk_content,'erDiagram\n EXTERNAL\n');await assert.rejects(s.act('draw','commit',{id:j.id,review:'pass',findings:[]}),/externally/);assert.equal(await readFile(file,'utf8'),'erDiagram\n EXTERNAL\n');});
test('visual correction cannot change constraints and automatic repairs stop after two',async()=>{const {s}=await fixture();const initial=await s.act('draw','stage',{version:s.version,saved_hash:s.savedHash,content:source});await ready(s,s.jobs.get(initial.id),'{"keys":["PK"]}');const first=await s.act('draw','stage',{version:s.version,saved_hash:s.savedHash,content:source,repair_of:initial.id,adjustment:'visual'});const rejected=await ready(s,s.jobs.get(first.id),'{"keys":["FK"]}');assert.equal(rejected.job.status,'error');const second=await s.act('draw','stage',{version:s.version,saved_hash:s.savedHash,content:source,repair_of:first.id,adjustment:'syntax'});await s.act('ui','report',{id:second.id,source_hash:second.source_hash,error:'syntax'});await assert.rejects(s.act('draw','stage',{version:s.version,saved_hash:s.savedHash,content:source,repair_of:second.id,adjustment:'syntax'}),/limit/);});
test('timeout and missing or corrupt images never count as ready',async()=>{const {s}=await fixture();const job=s.jobs.get(s.current);await assert.rejects(s.act('ui','report',{...image(job),png:''}),/PNG/);const broken=image(job);const bytes=Buffer.from(broken.png,'base64');bytes[bytes.length-10]^=1;broken.png=bytes.toString('base64');await assert.rejects(s.act('ui','report',broken));job.created=Date.now()-31000;s.expire();assert.equal(job.status,'error');await assert.rejects(ready(s,job),/stale/);});
test('concurrent revisions allow exactly one writer and theme cannot write through conflicts',async()=>{const {s,file}=await fixture();const n=s.version;const results=await Promise.allSettled([s.exclusive(()=>s.act('ui','draft',{version:n,content:source+'\n B'})),s.exclusive(()=>s.act('ui','draft',{version:n,content:source+'\n C'}))]);assert.equal(results.filter(r=>r.status==='fulfilled').length,1);await writeFile(file,'erDiagram\n EXTERNAL');await s.act('ui','theme',{version:s.version,theme:'dark'});await assert.rejects(ready(s),/externally/);assert.equal(await readFile(file,'utf8'),'erDiagram\n EXTERNAL');});
test('schema symlink replacement cannot redirect saved writes',async()=>{const {s,file,dir}=await fixture();const other=path.join(dir,'other.mmd');await writeFile(other,source);await unlink(file);await symlink(other,file);await assert.rejects(s.save(source+'\n B'),/path changed/);assert.equal(await readFile(other,'utf8'),source);});
test('real HTTP capabilities, origin, host, unknown inputs and upstream routes enforce isolation',async()=>{const {file}=await fixture();const {server,descriptor:d}=await startServer(file);try{const call=(role,action,method='POST',extra={})=>fetch(`${d.url}/api/camp/${action}`,{method,headers:{Authorization:`Bearer ${d.tokens[role]}`,'Content-Type':'application/json',...extra},...(method==='POST'?{body:'{}'}:{})});for(const action of ['draft','stage','commit','theme','reload','report'])assert.equal((await call('discuss',action)).status,403);assert.equal((await call('discuss','diagram','GET')).status,200);assert.equal((await call('draw','draft')).status,403);assert.equal((await call('ui','stage')).status,403);assert.equal((await call('ui','diagram','GET',{Origin:'https://foreign.invalid'})).status,403);assert.equal((await fetch(`${d.url}/api/set_diagram`)).status,403);assert.equal((await fetch(`${d.url}/api/camp/diagram`)).status,401);assert.equal((await fetch(`${d.url}/api/camp/reload`,{method:'POST',headers:{Authorization:`Bearer ${d.tokens.ui}`},body:'{"unexpected":true}'})).status,409);}finally{await new Promise(resolve=>server.close(resolve));}});
test('old renderer reports cannot win a pending job or revoke its review state',async()=>{const {file}=await fixture(),{server,session:s,descriptor:d}=await startServer(file);try{const body=image(s.jobs.get(s.current)),post=value=>fetch(`${d.url}/api/camp/report`,{method:'POST',headers:{Authorization:`Bearer ${d.tokens.ui}`,'Content-Type':'application/json'},body:JSON.stringify(value)});assert.equal((await post(body)).status,409);assert.equal(s.jobs.get(s.current).status,'pending');assert.equal(s.review.reason,'initial');assert.equal((await post({...body,renderer_version:3})).status,200);assert.equal(s.jobs.get(s.current).status,'ready');}finally{await new Promise(resolve=>server.close(resolve));}});

test('theme preference initialization is idempotent and stale explicit toggles are rejected',async()=>{
    const {s}=await fixture();const version=s.version;
    await s.act('ui','theme',{version,theme:'dark',initialize:true});const job=s.current;
    const state=await s.act('ui','theme',{version,theme:'light',initialize:true});
    assert.equal(state.theme,'dark');assert.equal(state.theme_initialized,true);assert.equal(s.current,job);
    await assert.rejects(s.act('ui','theme',{version,theme:'light'}),/revision changed/);
    await assert.rejects(s.act('ui','theme',{version:s.version,theme:'dark',initialize:'true'}),/initialization/);
});
test('resume preserves dark presentation and prevents a new viewer overriding it',async()=>{
    const {file}=await fixture();const first=await startServer(file);
    await first.session.act('ui','theme',{version:1,theme:'dark'});const state=await first.session.state();
    await new Promise(resolve=>first.server.close(resolve));
    const resumed=await startServer(file,{resume:{...first.descriptor,version:state.version+1,theme:state.theme,key_section:state.key_section}});
    try{const s=resumed.session;await s.act('ui','theme',{version:s.version,theme:'light',initialize:true});assert.equal(s.theme,'dark');assert.equal(s.jobs.get(s.current).theme,'dark');assert.equal((await s.state()).runtime_revision,2);}finally{await new Promise(resolve=>resumed.server.close(resolve));}
});
